language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: m/eDLJvlANbScPpcmHE1zUd9rb3WRwezjlUhCNgbHspYV1LVF2fZNS7lGk6X0G2GxWt/IQaoFh3u09fcSp5vEQFG64bsHUguH9eXVx40OZVY2koIOFieOFNqtlXu+FnExOe3MiVZMq+kd6QlvE4wYZFWgrGfLkRYw8Je5dbTWl56c/FUQHjD3Eyc9RugCNov+MpBzurfayXpr2VS+ed1PPQv6RON4k+lPr/0T4y1oq17np5t2abyVO/9gXHhFehKg21li1O+8a9ZU9Uat3nORZbNLKKfxyCiMgiyWzTqnrHQQK05XcfntZnCzST5CgnmxhoZFfowVF9zlBL9QjAABe5MAI6cALGXH16LdeVLmRlg7wN72AXN3LO8JqhuxkHh1hBK/QuLpoi6Y0O8c/0sMzOWw0qHVwTfsgvf6YtYlL8qxhzWgSoJ1lqxy3EOXmqu5imczOSJEEfmfsiDA4bJZodgte0zP+cc1qON3QyT13DDQaV6KdusX3wVvoahDpP6BtWYU4NArXo/yXjOjFZzUKcpTFJIkugBgp/K34++13htPIx5NoTH+uQ5n+s+MimdwTBTuCdTa8E8ZHAlBo7bIDfB/W34e8KXGzxI+N2O1+ObxQ7z6EPniFxSqdSL69NRtfbN8fC+e+HxbBhau/6nZ9KWfDBuVP0cvfYHBbrE2B4=
  app: stormy-refuge-67730
